<?php session_start();
?>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=`, initial-scale=1">
	 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
	<title>Deposit</title>
</head>
<body>
<style>
      body{
      
      background:URL("connected_dots_colorful_triangles.jpeg");
      }
	.tops{
			margin-top: 100px;
		}
</style>
<div class="columns">
	<div class="column is-offset-4">
		<h1 class="title has-text-white  pt-4"> SDCKBANK </h1>
	</div>
</div>

<div class="columns mt-6">
	<div class="card has-background-success column is-offset-3 is-7">
		<header class="title">TRANSFER SUCCESSFULLY </header>

		<a href="userpanel.php">back to homepage</a>
	</div>
</div>
</form>
</body>
</html>